const actionTypes = {
  LOAD_BOARDS: "LOAD_BOARDS",
  ADD_BOARD: "ADD_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  ADD_BOARD_ITEM: "ADD_BOARD_ITEM",
  DELETE_BOARD_ITEM: "DELETE_BOARD_ITEM",
  TOGGLE_ADD_BOARD_VIEW: "TOGGLE_ADD_BOARD_VIEW"
};

export default actionTypes;
